import type { ReactNode } from 'react'
import { AlertCircle, ArrowDownLeft, ArrowUpRight, Check, ChevronLeft, ChevronRight, Inbox, LoaderCircle, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { errorMessage } from '@/lib/api'
import type { Movement, Stock } from '@/lib/types'
import { dateTime, quantity } from '@/lib/quantity'

export function PageHeading({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: ReactNode }) {
  return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-bold tracking-[.17em] text-primary uppercase">{eyebrow}</p><h1 className="text-[29px] leading-tight font-semibold tracking-[-1px]">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div><div className="flex gap-2">{children}</div></div>
}
export function ErrorNotice({ error, retry }: { error: unknown; retry?: () => void }) {
  if (!error) return null
  return <div role="alert" className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mt-0.5 size-4 shrink-0"/><div className="flex-1">{errorMessage(error)}</div>{retry && <button type="button" className="shrink-0 font-semibold underline" onClick={retry}>Tentar novamente</button>}</div>
}
export function Loading({ label = 'Carregando informações…' }: { label?: string }) { return <div role="status" className="flex min-h-40 items-center justify-center gap-3 p-8 text-muted-foreground"><LoaderCircle className="size-5 animate-spin"/>{label}</div> }
export function Empty({ title, description, children }: { title: string; description: string; children?: ReactNode }) { return <div className="flex min-h-64 flex-col items-center justify-center px-6 py-10 text-center"><div className="mb-4 rounded-2xl border bg-background p-4"><Inbox className="size-6 text-slate-400"/></div><h3 className="font-semibold">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p>{children && <div className="mt-5">{children}</div>}</div> }
export function SearchInput({ value, onChange, placeholder = 'Pesquisar por nome ou código…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="relative min-w-48 flex-1"><Search className="pointer-events-none absolute top-3 left-3 size-4 text-slate-400"/><Input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="h-10 bg-white pl-10"/></div> }
export function Field({ label, id, hint, children }: { label: string; id: string; hint?: string; children: ReactNode }) { return <div className="space-y-2"><Label htmlFor={id} className="text-[13px] font-medium">{label}</Label>{children}{hint && <p id={`${id}-hint`} className="text-xs leading-5 text-muted-foreground">{hint}</p>}</div> }
export function NativeSelect(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`h-10 w-full rounded-md border border-input bg-white px-3 text-sm disabled:opacity-50 ${props.className || ''}`}/> }
export function SubmitButton({ pending, children }: { pending: boolean; children: ReactNode }) { return <Button type="submit" disabled={pending}>{pending && <LoaderCircle className="size-4 animate-spin"/>}{children}</Button> }
export function SuccessNotice({ children }: { children: ReactNode }) { return <div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><Check className="size-4"/>{children}</div> }
export function Pagination({ page, total, pageSize, onChange }: { page: number; total: number; pageSize: number; onChange: (page: number) => void }) {
  const pages = Math.max(1, Math.ceil(total / pageSize))
  return <div className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4 text-xs text-muted-foreground"><span>{total ? `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, total)} de ${total} registros` : '0 registros'}</span><div className="flex items-center gap-3"><span>Página {page} de {pages}</span><Button variant="outline" size="icon" className="size-8" aria-label="Página anterior" disabled={page <= 1} onClick={() => onChange(page - 1)}><ChevronLeft className="size-4"/></Button><Button variant="outline" size="icon" className="size-8" aria-label="Próxima página" disabled={page >= pages} onClick={() => onChange(page + 1)}><ChevronRight className="size-4"/></Button></div></div>
}
export function StockBadge({ status }: { status: Stock['status'] }) { const labels = { Healthy: 'Regular', Low: 'Estoque baixo', Empty: 'Sem estoque' }; return <Badge variant="outline" className={status === 'Healthy' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : status === 'Low' ? 'border-amber-100 bg-amber-50 text-amber-700' : 'border-red-100 bg-red-50 text-red-700'}><span className="size-1.5 rounded-full bg-current"/>{labels[status]}</Badge> }
export function MovementRows({ items, compact = false }: { items: Movement[]; compact?: boolean }) {
  return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y bg-slate-50/80 text-[11px] text-muted-foreground"><tr><th className="px-5 py-3 font-semibold">MOVIMENTAÇÃO</th><th className="px-4 py-3 font-semibold">PRODUTO / LOCAL</th><th className="px-4 py-3 text-right font-semibold">QUANTIDADE</th>{!compact && <th className="px-4 py-3 font-semibold">RESPONSÁVEL / REFERÊNCIA</th>}<th className="px-5 py-3 font-semibold">DATA</th></tr></thead><tbody className="divide-y">{items.map(item => <tr key={item.id} className="hover:bg-slate-50/60"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className={`rounded-lg p-2 ${item.type === 'Receipt' ? 'bg-emerald-50 text-emerald-700' : 'bg-indigo-50 text-indigo-600'}`}>{item.type === 'Receipt' ? <ArrowDownLeft className="size-4"/> : <ArrowUpRight className="size-4"/>}</span><div className="whitespace-nowrap font-medium">{item.type === 'Receipt' ? 'Entrada' : 'Consumo'}<p className="mt-0.5 text-[11px] font-normal text-muted-foreground">#{item.number}</p></div></div></td><td className="px-4 py-4"><p className="min-w-36 font-medium">{item.productName}</p><p className="mt-1 text-xs text-muted-foreground">{item.locationPath}</p></td><td className={`px-4 py-4 text-right whitespace-nowrap tabular font-semibold ${item.type === 'Receipt' ? 'text-emerald-700' : 'text-slate-700'}`}>{item.type === 'Receipt' ? '+' : '−'}{quantity(item.quantity)} <span className="text-xs font-normal text-muted-foreground">{item.unit}</span></td>{!compact && <td className="px-4 py-4"><p>{item.actorName}</p><p className="mt-1 text-xs text-muted-foreground">{item.recipient || item.reference || '—'}</p>{item.notes && <p className="mt-1 max-w-xs text-xs text-muted-foreground">{item.notes}</p>}</td>}<td className="px-5 py-4 text-xs whitespace-nowrap text-muted-foreground">{dateTime(item.createdAt)}</td></tr>)}</tbody></table></div>
}
